# Necessary
response_key: 'response'
error_key: 'error'
id_key:
  - 'uuid'
  - 'question'
prompt_key: 'prompt'

# Optional
history_key: 'history'
status_key: 'status'

save_prompt: True
max_tokens: 4096
max_rounds: 10
